use crate::catalog::Catalog;
use regex::Regex;
use std::collections::BTreeMap;

/// What we were able to work out about a single variable.
#[derive(Debug, Default, PartialEq)]
struct Inferred {
    pattern: Option<String>,
    source: Option<String>,
    description: Option<String>,
    secret: bool,
    /// Rendered as a comment for the user to complete, never as a live constraint.
    todo: Option<String>,
}

pub fn generate(vars: &BTreeMap<String, String>, catalog: &Catalog) -> String {
    let mut out = String::from(
        "# Generated by `dottyenv init`.\n\
         #\n\
         # Commit this file. It describes the shape of your configuration, not its\n\
         # values, so it contains no secrets.\n\
         #\n\
         # Every variable was marked `required` because it was present in the source\n\
         # file. Loosen anything that is actually optional.\n\n\
         [meta]\nversion = 1\n",
    );

    for (name, value) in vars {
        let inferred = infer(name, value, catalog);
        out.push('\n');
        out.push_str(&render_var(name, &inferred));
    }

    out
}

fn infer(name: &str, value: &str, catalog: &Catalog) -> Inferred {
    // 1. The catalog is the only source of external knowledge, so it wins.
    if let Some(provider) = catalog.find(name, value) {
        return Inferred {
            pattern: provider.pattern.clone(),
            source: provider.source.clone(),
            description: Some(provider.name.clone()),
            secret: provider.secret,
            todo: None,
        };
    }

    let secret = looks_secret(name);

    // 2. A URL scheme is an unambiguous structural signal.
    if let Some(scheme) = url_scheme(value) {
        return Inferred {
            pattern: Some(format!("^{scheme}://")),
            secret,
            ..Default::default()
        };
    }

    // 3. Everything else gets no pattern. Inferring one from a single sample
    //    would reject valid values later (PRD §7.4).
    let todo = if is_bool(value) {
        None
    } else if is_enum_like(value) && !secret {
        // Never echo a secret's value back, even as a suggestion.
        Some(format!(
            "one_of = [{value:?}, ...]  # TODO: list the valid values, then uncomment"
        ))
    } else {
        Some("TODO: add a pattern, or delete this line".to_string())
    };

    Inferred {
        secret,
        todo,
        ..Default::default()
    }
}

/// Names are a reliable signal for secrecy even when the value tells us nothing.
fn looks_secret(name: &str) -> bool {
    const MARKERS: [&str; 6] = [
        "SECRET",
        "TOKEN",
        "PASSWORD",
        "PRIVATE",
        "_KEY",
        "CREDENTIAL",
    ];
    let upper = name.to_uppercase();
    MARKERS.iter().any(|m| upper.contains(m))
}

fn url_scheme(value: &str) -> Option<String> {
    let re = Regex::new(r"^([a-z][a-z0-9+.\-]*)://").expect("static regex");
    re.captures(value).map(|caps| regex::escape(&caps[1]))
}

fn is_bool(value: &str) -> bool {
    matches!(value.to_lowercase().as_str(), "true" | "false" | "1" | "0")
}

/// Short, lowercase, alphabetic values are usually one of a small set.
fn is_enum_like(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 12
        && value.chars().all(|c| c.is_ascii_lowercase() || c == '-')
}

fn render_var(name: &str, inferred: &Inferred) -> String {
    let mut out = format!("[vars.{}]\n", toml_key(name));
    out.push_str("required    = true\n");

    if let Some(pattern) = &inferred.pattern {
        out.push_str(&format!("pattern     = {}\n", toml_string(pattern)));
    }
    if let Some(description) = &inferred.description {
        out.push_str(&format!("description = {}\n", toml_string(description)));
    }
    if let Some(source) = &inferred.source {
        out.push_str(&format!("source      = {}\n", toml_string(source)));
    }
    if inferred.secret {
        out.push_str("secret      = true\n");
    }
    if let Some(todo) = &inferred.todo {
        out.push_str(&format!("# {todo}\n"));
    }

    out
}

/// Prefer a literal string so backslash-heavy regexes stay readable.
fn toml_string(value: &str) -> String {
    if !value.contains('\'') && !value.contains('\n') {
        format!("'{value}'")
    } else {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

fn toml_key(name: &str) -> String {
    let bare = !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-');
    if bare {
        name.to_string()
    } else {
        format!("\"{}\"", name.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::Schema;

    fn catalog() -> Catalog {
        Catalog::load().unwrap()
    }

    fn env(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    #[test]
    fn output_is_always_a_parseable_schema() {
        let vars = env(&[
            ("DATABASE_URL", "postgres://localhost/app"),
            ("STRIPE_SECRET_KEY", "sk_test_abc"),
            ("LOG_LEVEL", "info"),
            ("MYSTERY", "8f3a9c2e1b4d7f60"),
            ("DEBUG", "true"),
        ]);
        let generated = generate(&vars, &catalog());
        let schema: Schema = toml::from_str(&generated)
            .unwrap_or_else(|e| panic!("generated schema does not parse: {e}\n\n{generated}"));
        assert_eq!(schema.vars.len(), 5);
    }

    #[test]
    fn catalog_hit_brings_pattern_source_and_secret() {
        let inferred = infer("STRIPE_SECRET_KEY", "sk_test_abc", &catalog());
        assert_eq!(inferred.pattern.as_deref(), Some("^(sk|rk)_(test|live)_"));
        assert!(inferred.source.is_some());
        assert!(inferred.secret);
    }

    #[test]
    fn unknown_url_gets_a_scheme_pattern() {
        let inferred = infer("BROKER", "amqp://guest@localhost", &catalog());
        assert_eq!(inferred.pattern.as_deref(), Some("^amqp://"));
    }

    /// The core rule of PRD §7.4.
    #[test]
    fn never_invents_a_pattern_from_an_opaque_value() {
        let inferred = infer("MYSTERY", "8f3a9c2e1b4d7f60", &catalog());
        assert_eq!(inferred.pattern, None);
        assert!(inferred.todo.is_some());
    }

    #[test]
    fn marks_secrets_by_name_when_the_value_is_uninformative() {
        assert!(infer("SESSION_SECRET", "changeme", &catalog()).secret);
        assert!(infer("API_TOKEN", "changeme", &catalog()).secret);
        assert!(!infer("PORT", "8080", &catalog()).secret);
    }

    #[test]
    fn suggests_one_of_for_enum_like_values_but_only_as_a_comment() {
        let inferred = infer("LOG_LEVEL", "info", &catalog());
        assert!(inferred.todo.as_deref().unwrap().contains("one_of"));
        // Must not become a live constraint: we only ever saw one value.
        assert!(inferred.pattern.is_none());
    }

    /// "changeme" is enum-like (short, all lowercase), so without the secret guard
    /// it would be echoed back inside a one_of suggestion.
    #[test]
    fn never_echoes_a_secret_value_into_the_schema() {
        let vars = env(&[("SESSION_SECRET", "changeme")]);
        let generated = generate(&vars, &catalog());
        assert!(!generated.contains("changeme"), "{generated}");
    }

    #[test]
    fn todo_comments_are_not_double_hashed() {
        let vars = env(&[("MYSTERY_HASH", "8f3a9c2e1b4d7f60")]);
        let generated = generate(&vars, &catalog());
        assert!(!generated.contains("# #"), "{generated}");
    }

    #[test]
    fn generated_schema_validates_the_env_it_came_from() {
        let vars = env(&[
            ("DATABASE_URL", "postgres://localhost/app"),
            ("STRIPE_SECRET_KEY", "sk_test_abc"),
            ("MYSTERY", "8f3a9c2e1b4d7f60"),
        ]);
        let schema: Schema = toml::from_str(&generate(&vars, &catalog())).unwrap();
        let report = crate::check::check(&schema.resolve(None), &vars);
        assert!(
            report.is_ok(),
            "init produced a schema its own input fails: {:?}",
            report.findings
        );
    }

    #[test]
    fn quotes_keys_that_are_not_bare() {
        let vars = env(&[("WEIRD.NAME", "x")]);
        let schema: Schema = toml::from_str(&generate(&vars, &catalog())).unwrap();
        assert!(schema.vars.contains_key("WEIRD.NAME"));
    }
}
